import Foundation

public final class LocalizationManager: Sendable {
    public static let shared = LocalizationManager()

    private let strings: [String: [String: String]] = [
        "en": [
            "tab_generator": "Generator",
            "tab_gallery": "Character Gallery",
            "tab_preferences": "Preferences",
            "tab_logs": "Diagnostics & Logs",
            "workflow": "WORKFLOW",
            "resources": "RESOURCES",
            "studio_title": "Studio Dashboard",
            "studio_subtitle": "High-performance character tracking & scenepack extractor",
            "mode_real_faces": "Live Action / Real Faces",
            "mode_anime": "2D Animation / Anime",
            "quick_presets": "Quick Presets:",
            "custom_presets": "Custom Presets...",
            "preset_tiktok": "TikTok (9:16)",
            "preset_youtube": "YouTube (16:9)",
            "preset_draft": "Draft (Fast)",
            "timing_margins": "Timing & Scene Margins",
            "pad_before": "Pad Before",
            "pad_after": "Pad After",
            "gap_bridge": "Gap Bridge",
            "min_scene": "Min Scene",
            "scan_speed": "Scan Speed & Framing",
            "frame_skip": "Frame Skip",
            "aspect_ratio": "Aspect Ratio",
            "export_quality": "Export Quality",
            "dialogue_vad": "Dialogue & Voice Protection",
            "vad_speech": "VAD Speech Protection",
            "voice_similarity": "Voice Similarity",
            "buffer": "Buffer:",
            "automation_audio": "Automation & Audio Tracks",
            "skip_intro": "Skip Intro",
            "skip_outro": "Skip Outro",
            "auto_render": "Auto-Render after scan",
            "audio_track": "Audio Track:",
            "scan_button": "Scan and Analyze Video",
            "cancel_button": "Stop / Cancel Process",
            "ready_status": "Ready to analyze footage",
            "appearance_theme": "Appearance & Accent Theme",
            "select_accent": "Select Accent Color",
            "power_sleep": "Power & System Sleep",
            "sleep_toggle": "Inhibit system & display sleep during active jobs",
            "sleep_desc": "Keeps your Mac awake while scanning or rendering long video scenepacks.",
            "lang_section": "Language & Localization",
            "interface_lang": "Interface Language",
            "diagnostics_section": "Diagnostics & Logs",
            "copy_report": "Copy Diagnostic Report",
            "input_footage": "Input Video Footage",
            "drop_video": "Click to select video or drag & drop MKV/MP4 files here",
            "target_reference": "Target Character Reference",
            "drop_image": "Drop face image or select from Gallery",
            "save_location": "Export Scenepack Save Location",
            "auto_desktop": "Auto (Destination folder or Desktop)"
        ],
        "pl": [
            "tab_generator": "Generator",
            "tab_gallery": "Galeria Postaci",
            "tab_preferences": "Preferencje",
            "tab_logs": "Diagnostyka i Logi",
            "workflow": "PROCES PRACY",
            "resources": "ZASOBY",
            "studio_title": "Panel Główny Studio",
            "studio_subtitle": "Wysokowydajne śledzenie postaci i wycinanie scenepacków",
            "mode_real_faces": "Film / Ludzkie Twarze",
            "mode_anime": "Animacja 2D / Anime",
            "quick_presets": "Szybkie Profile:",
            "custom_presets": "Własne Profile...",
            "preset_tiktok": "TikTok (9:16)",
            "preset_youtube": "YouTube (16:9)",
            "preset_draft": "Szybki Szkic (Draft)",
            "timing_margins": "Czas i Marginesy Sceny",
            "pad_before": "Margines przed",
            "pad_after": "Margines po",
            "gap_bridge": "Łączenie przerw",
            "min_scene": "Min. długość",
            "scan_speed": "Szybkość i Kadrowanie",
            "frame_skip": "Krok klatek",
            "aspect_ratio": "Proporcje",
            "export_quality": "Jakość wideo",
            "dialogue_vad": "Ochrona Dialogu i Głosu",
            "vad_speech": "Ochrona mowy (VAD)",
            "voice_similarity": "Zgodność głosu",
            "buffer": "Bufor:",
            "automation_audio": "Automatyzacja i Ścieżki Audio",
            "skip_intro": "Pomiń Opening",
            "skip_outro": "Pomiń Ending",
            "auto_render": "Automatyczny render po skanie",
            "audio_track": "Ścieżka audio:",
            "scan_button": "Skanuj i Analizuj Wideo",
            "cancel_button": "Zatrzymaj / Anuluj",
            "ready_status": "Gotowy do analizy materiału",
            "appearance_theme": "Wygląd i Kolor Akcentu",
            "select_accent": "Wybierz Kolor Akcentu",
            "power_sleep": "Zasilanie i Usypianie Systemu",
            "sleep_toggle": "Blokuj usypianie systemu i ekranu podczas pracy",
            "sleep_desc": "Utrzymuje Twój Mac wybudzony podczas skanowania i renderowania scenepacków.",
            "lang_section": "Język i Lokalizacja",
            "interface_lang": "Język Interfejsu",
            "diagnostics_section": "Diagnostyka i Logi",
            "copy_report": "Kopiuj Raport Diagnostyczny",
            "input_footage": "Wejściowy Plik Wideo",
            "drop_video": "Kliknij, aby wybrać wideo lub upuść pliki MKV/MP4 tutaj",
            "target_reference": "Referencja Twarzy Postaci",
            "drop_image": "Upuść zdjęcie twarzy lub wybierz z Galerii",
            "save_location": "Lokalizacja Zapisu Scenepacka",
            "auto_desktop": "Automatycznie (Katalog docelowy lub Biurko)"
        ],
        "de": [
            "tab_generator": "Generator",
            "tab_gallery": "Charakter-Galerie",
            "tab_preferences": "Einstellungen",
            "tab_logs": "Diagnose & Logs",
            "workflow": "WORKFLOW",
            "resources": "RESSOURCEN",
            "studio_title": "Studio Übersicht",
            "studio_subtitle": "Hochleistungs-Charakterverfolgung & Scenepack-Extraktor",
            "mode_real_faces": "Realfilm / Echte Gesichter",
            "mode_anime": "2D-Animation / Anime",
            "quick_presets": "Schnellprofile:",
            "custom_presets": "Eigene Profile...",
            "preset_tiktok": "TikTok (9:16)",
            "preset_youtube": "YouTube (16:9)",
            "preset_draft": "Entwurf (Schnell)",
            "timing_margins": "Timing & Szenenränder",
            "pad_before": "Vorlauf",
            "pad_after": "Nachlauf",
            "gap_bridge": "Lückentoleranz",
            "min_scene": "Min. Länge",
            "scan_speed": "Scangeschwindigkeit & Bildausschnitt",
            "frame_skip": "Frame-Sprung",
            "aspect_ratio": "Seitenverhältnis",
            "export_quality": "Exportqualität",
            "dialogue_vad": "Dialog- & Stimmschutz",
            "vad_speech": "Sprachaktivität (VAD)",
            "voice_similarity": "Stimmabgleich",
            "buffer": "Puffer:",
            "automation_audio": "Automatisierung & Tonspuren",
            "skip_intro": "Intro überspringen",
            "skip_outro": "Outro überspringen",
            "auto_render": "Nach Scan automatisch rendern",
            "audio_track": "Tonspur:",
            "scan_button": "Video scannen und analysieren",
            "cancel_button": "Vorgang abbrechen",
            "ready_status": "Bereit zur Videoanalyse",
            "appearance_theme": "Erscheinungsbild & Akzentfarbe",
            "select_accent": "Akzentfarbe auswählen",
            "power_sleep": "Energie & Ruhezustand",
            "sleep_toggle": "Ruhezustand während der Verarbeitung verhindern",
            "sleep_desc": "Hält Ihren Mac während des Scannens oder Renderns aktiv.",
            "lang_section": "Sprache & Lokalisierung",
            "interface_lang": "Oberflächensprache",
            "diagnostics_section": "Diagnose & Protokolle",
            "copy_report": "Diagnosebericht kopieren",
            "input_footage": "Videomaterial",
            "drop_video": "Klicken oder MKV/MP4-Dateien hier ablegen",
            "target_reference": "Charakter-Referenzbild",
            "drop_image": "Gesichtsbild ablegen oder aus Galerie wählen",
            "save_location": "Speicherort für Scenepack",
            "auto_desktop": "Automatisch (Zielordner oder Schreibtisch)"
        ],
        "es": [
            "tab_generator": "Generador",
            "tab_gallery": "Galería de Personajes",
            "tab_preferences": "Preferencias",
            "tab_logs": "Diagnóstico y Registros",
            "workflow": "FLUJO DE TRABAJO",
            "resources": "RECURSOS",
            "studio_title": "Panel de Estudio",
            "studio_subtitle": "Seguimiento de personajes de alto rendimiento y extractor de scenepacks",
            "mode_real_faces": "Acción Real / Rostros",
            "mode_anime": "Animación 2D / Anime",
            "quick_presets": "Ajustes Rápidos:",
            "custom_presets": "Ajustes Personalizados...",
            "preset_tiktok": "TikTok (9:16)",
            "preset_youtube": "YouTube (16:9)",
            "preset_draft": "Borrador (Rápido)",
            "timing_margins": "Tiempos y Márgenes de Escena",
            "pad_before": "Margen previo",
            "pad_after": "Margen posterior",
            "gap_bridge": "Puente de pausas",
            "min_scene": "Escena mínima",
            "scan_speed": "Velocidad de Escaneo y Encuadre",
            "frame_skip": "Salto de fotogramas",
            "aspect_ratio": "Relación de aspecto",
            "export_quality": "Calidad de exportación",
            "dialogue_vad": "Protección de Diálogo y Voz",
            "vad_speech": "Protección de voz (VAD)",
            "voice_similarity": "Similitud de voz",
            "buffer": "Búfer:",
            "automation_audio": "Automatización y Pistas de Audio",
            "skip_intro": "Omitir intro",
            "skip_outro": "Omitir créditos",
            "auto_render": "Renderizado automático tras escaneo",
            "audio_track": "Pista de audio:",
            "scan_button": "Escanear y Analizar Video",
            "cancel_button": "Detener / Cancelar",
            "ready_status": "Listo para analizar metraje",
            "appearance_theme": "Apariencia y Tema de Acento",
            "select_accent": "Seleccionar Color de Acento",
            "power_sleep": "Energía y Reposo del Sistema",
            "sleep_toggle": "Evitar reposo del sistema y pantalla durante tareas",
            "sleep_desc": "Mantiene tu Mac despierto durante el escaneo y renderizado.",
            "lang_section": "Idioma y Localización",
            "interface_lang": "Idioma de la Interfaz",
            "diagnostics_section": "Diagnóstico y Registros",
            "copy_report": "Copiar Informe de Diagnóstico",
            "input_footage": "Metraje de Video de Entrada",
            "drop_video": "Haz clic o arrastra archivos MKV/MP4 aquí",
            "target_reference": "Referencia del Personaje",
            "drop_image": "Arrastra una imagen de rostro o elige de la Galería",
            "save_location": "Ubicación de Guardado",
            "auto_desktop": "Automático (Carpeta de destino o Escritorio)"
        ],
        "fr": [
            "tab_generator": "Générateur",
            "tab_gallery": "Galerie de Personnages",
            "tab_preferences": "Préférences",
            "tab_logs": "Diagnostics et Journaux",
            "workflow": "FLUX DE TRAVAIL",
            "resources": "RESSOURCES",
            "studio_title": "Tableau de Bord Studio",
            "studio_subtitle": "Suivi de personnages haute performance et extracteur de scenepacks",
            "mode_real_faces": "Prise de Vue Réelle / Visages",
            "mode_anime": "Animation 2D / Anime",
            "quick_presets": "Préréglages Rapides :",
            "custom_presets": "Préréglages Personnalisés...",
            "preset_tiktok": "TikTok (9:16)",
            "preset_youtube": "YouTube (16:9)",
            "preset_draft": "Brouillon (Rapide)",
            "timing_margins": "Timing et Marges de Scène",
            "pad_before": "Marge avant",
            "pad_after": "Marge après",
            "gap_bridge": "Raccord d'écarts",
            "min_scene": "Scène minimale",
            "scan_speed": "Vitesse d'Analyse et Cadrage",
            "frame_skip": "Saut d'images",
            "aspect_ratio": "Format d'image",
            "export_quality": "Qualité d'exportation",
            "dialogue_vad": "Protection du Dialogue et Voix",
            "vad_speech": "Protection vocale (VAD)",
            "voice_similarity": "Similarité vocale",
            "buffer": "Tampon :",
            "automation_audio": "Automatisation et Pistes Audio",
            "skip_intro": "Ignorer l'intro",
            "skip_outro": "Ignorer l'outro",
            "auto_render": "Rendu automatique après analyse",
            "audio_track": "Piste audio :",
            "scan_button": "Analyser et Scanner la Vidéo",
            "cancel_button": "Arrêter / Annuler",
            "ready_status": "Prêt à analyser la vidéo",
            "appearance_theme": "Apparence et Couleur d'Accent",
            "select_accent": "Sélectionner la Couleur d'Accent",
            "power_sleep": "Alimentation et Veille Système",
            "sleep_toggle": "Empêcher la veille du Mac pendant les tâches actives",
            "sleep_desc": "Garde votre Mac éveillé pendant l'analyse et le rendu vidéo.",
            "lang_section": "Langue et Localisation",
            "interface_lang": "Langue de l'Interface",
            "diagnostics_section": "Diagnostics et Journaux",
            "copy_report": "Copier le Rapport de Diagnostic",
            "input_footage": "Vidéo Source",
            "drop_video": "Cliquez pour choisir ou glissez-déposez MKV/MP4 ici",
            "target_reference": "Référence du Visage",
            "drop_image": "Déposez une image ou choisissez dans la Galerie",
            "save_location": "Emplacement d'Exportation",
            "auto_desktop": "Automatique (Dossier source ou Bureau)"
        ],
        "ja": [
            "tab_generator": "ジェネレーター",
            "tab_gallery": "キャラクターギャラリー",
            "tab_preferences": "環境設定",
            "tab_logs": "診断とログ",
            "workflow": "ワークフロー",
            "resources": "リソース",
            "studio_title": "スタジオダッシュボード",
            "studio_subtitle": "高性能キャラクター追跡＆シーンパック抽出",
            "mode_real_faces": "実写 / 人物の顔",
            "mode_anime": "2Dアニメーション / アニメ",
            "quick_presets": "クイックプリセット:",
            "custom_presets": "カスタムプリセット...",
            "preset_tiktok": "TikTok (9:16)",
            "preset_youtube": "YouTube (16:9)",
            "preset_draft": "ドラフト (高速)",
            "timing_margins": "タイミングとシーンマージン",
            "pad_before": "前マージン",
            "pad_after": "後マージン",
            "gap_bridge": "ギャップ結合",
            "min_scene": "最短シーン長",
            "scan_speed": "スキャン速度とフレーミング",
            "frame_skip": "フレームスキップ",
            "aspect_ratio": "アスペクト比",
            "export_quality": "出力品質",
            "dialogue_vad": "音声対話保護 (VAD)",
            "vad_speech": "音声検出保護 (VAD)",
            "voice_similarity": "声紋一致度",
            "buffer": "バッファ:",
            "automation_audio": "自動化とオーディオトラック",
            "skip_intro": "OPをスキップ",
            "skip_outro": "EDをスキップ",
            "auto_render": "スキャン後自動レンダリング",
            "audio_track": "音声トラック:",
            "scan_button": "動画をスキャンして分析",
            "cancel_button": "処理を停止 / キャンセル",
            "ready_status": "動画分析の準備完了",
            "appearance_theme": "外観とアクセントカラー",
            "select_accent": "アクセントカラーを選択",
            "power_sleep": "電源とシステムスリープ",
            "sleep_toggle": "作業中のスリープを防止",
            "sleep_desc": "スキャンおよびレンダリング中にMacがスリープするのを防ぎます。",
            "lang_section": "言語と地域",
            "interface_lang": "インターフェース言語",
            "diagnostics_section": "診断とログ",
            "copy_report": "診断レポートをコピー",
            "input_footage": "入力動画ファイル",
            "drop_video": "クリックして選択またはMKV/MP4をドロップ",
            "target_reference": "対象キャラクターの顔画像",
            "drop_image": "顔画像をドロップまたはギャラリーから選択",
            "save_location": "保存先フォルダ",
            "auto_desktop": "自動 (保存先またはデスクトップ)"
        ]
    ]

    public func string(for key: String, language: String) -> String {
        let langCode: String
        switch language.lowercased() {
        case "polski", "pl": langCode = "pl"
        case "deutsch", "de": langCode = "de"
        case "español", "es": langCode = "es"
        case "français", "fr": langCode = "fr"
        case "日本語", "ja": langCode = "ja"
        default: langCode = "en"
        }

        if let dict = strings[langCode], let val = dict[key] {
            return val
        }
        return strings["en"]?[key] ?? key
    }
}
